# Generated by Django 4.0.1 on 2023-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=500)),
                ('degree', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=20)),
                ('institute', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
            ],
        ),
    ]
